### ISSUE TITLE
[low priority] [Techniques index page] bullets for lists

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag-redesign#17]
I think use bullets or at least hanging indents so the lists are more readable with large font or small screen that causes lots of wrapping

![image](https://user-images.githubusercontent.com/6991814/185210657-d7e31c57-2d75-4768-803b-a3864b5dc623.png)

**Comment by michael-n-cooper** [comment]
I need 1) a choice between bullets or hanging indents 2) the HTML and CSS needed for that.

**Comment by shawna-slh** [comment]
* [ ] for now, change:
```
<ul class="toc-wcag-docs">
```

to:
```
<ul>
```

optionally, could delete this from your base.css :

```
.toc-wcag-docs {
	list-style: none;
	padding-left: 0;
}
.toc-wcag-docs a:visited {
	color: #036; /* make same as not visited, because visually same more important than indication of visited here */
}
```

/me not convinced of "visually same more important than indication of visited here"

**Comment by shawna-slh** [comment]
LOW priority for later: remove left padding/margin before bullet and keep hanging indent
