### ISSUE TITLE
[Understanding index page] add page contents box

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag-redesign#19]
_[Milestone -note: maybe not easy, but fairly big impact on usability... maybe Steve and Shawn can help?]_

add page contents box that includes POUR and the guidelines

see:
* [structure issue](https://github.com/w3c/wcag-redesign/issues/6)
* [example of multi-level Page Contents](https://www.w3.org/WAI/media/av/av-content/#toc)

**Comment by michael-n-cooper** [comment]
I need the specific HTML for the box, and specific filtering instructions for what show go in it, along with an example of the intended output.

**Comment by shawna-slh** [comment]
code related to https://github.com/w3c/wcag-redesign/pull/1

**Comment by shawna-slh** [comment]
content: all h2s on a page

**Comment by shawna-slh** [comment]
addressed in https://github.com/w3c/wcag-redesign/pull/38
