### ISSUE TITLE
content bug

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag-redesign#22]
e.g., from https://wai-wcag-redesign.netlify.app/understanding/non-text-content 
![image](https://user-images.githubusercontent.com/6991814/185652523-abf3d911-3d14-4833-a926-3131a51e5e9b.png)

**Comment by michael-n-cooper** [comment]
Fixed by https://github.com/w3c/wcag/commit/2bf3f43ed3750b3f5969b80b4bce04dc119fb7ce
