### ISSUE TITLE
[Understanding index page] link guidelines to their subpage

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag-redesign#4]
<img width="500" alt="guidelines pointed to" src="https://user-images.githubusercontent.com/6991814/185008207-ecf8b07b-7c3d-4204-95a8-a345bddba6d8.png">

**Comment by michael-n-cooper** [comment]
The guideline names are linked in the TOC. Somebody styled them without underlines. I need to know what class to use on which elements in the output instead, or have the CSS designers update the CSS.

**Comment by shawna-slh** [comment]
Well, I'm not the CSS designer, yet this OR seems to fix it: https://github.com/w3c/wcag-redesign/pull/25

**Comment by shawna-slh** [comment]
closing this as addressed in https://github.com/w3c/wcag-redesign/pull/25
