### ISSUE TITLE
[Understanding About page] Needs edit to remove redundancies and add appropriate headings

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag-redesign#5]
https://draft-wcag-redesign.netlify.app/understanding/about

* [ ] add a heading after the Summary
* [ ] edit to remove redundancies
* [ ] delete the double backets, e.g., [[WCAG20]]
* [ ] Start out with the following for people who land here and have no idea what WCAG even is: 

```
<p>Web Content Accessibility Guidelines (WCAG) provides requirements for making websites, applications, and other digital content accessible to people with disabilities. It is introduced in the <a href="https://www.w3.org/WAI/standards-guidelines/wcag/">WCAG 2 Overview <svg focusable="false" aria-hidden="true" class="icon-different-view "><use xlink:href="/WAI/assets/images/icons.svg#icon-different-view"></use></svg></a>.</p>

<p>There are additional resources that help you understand and implement WCAG. These Understanding documents are one type of resource. Others are explained in the <a href="https://www.w3.org/WAI/standards-guidelines/wcag/docs/">WCAG 2 Documents <svg focusable="false" aria-hidden="true" class="icon-different-view "><use xlink:href="/WAI/assets/images/icons.svg#icon-different-view"></use></svg></a>.</p>
```

**Comment by michael-n-cooper** [comment]
I will need the specific changes you want. The best option is to make a PR on the file: https://github.com/w3c/wcag/blob/redesign/understanding/about.html

**Comment by shawna-slh** [comment]
Unfortunately I was not able to make the time to make specific edit suggestions for this. And no one else did either.

**Comment by michael-n-cooper** [comment]
From what I can see in the PR diff, the edits to the understanding/about would require some coding, not a copy-paste as I hoped

**Comment by shawna-slh** [comment]
did first pass at most and created issues for other in main wcag repo
