### ISSUE TITLE
[Understanding index page] structure

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag-redesign#6]
Current draft has:
* h2: Understanding Guidelines and Success Criteria
  * h3: Perceivable
     * list: guideline
       * nested list: success criteria linked
* h2: Other Understanding documents
  * list

I'm thinking this would be better:

* h2: Perceivable
  * h3: guideline linked
    * list: success criteria linked
* h2: Understanding Conformance
* h2: Other Understanding Documents (if needed, see [which not](https://github.com/w3c/wcag-redesign/issues/11))
  * list

**Comment by michael-n-cooper** [comment]
Changing the heading levels and list organization is doable but needs care.

Pulling the Understanding Conformance page into a different level than it would otherwise land requires special casing which will be error prone. I recommend not doing it; at any rate it raises the difficulty level of the request.

**Comment by michael-n-cooper** [comment]
There doesn't seem to be a place in the PR where I can what the exact change request is for this. And I am not able to look at a rendered version and reliably notice what you want me to notice.

**Comment by shawna-slh** [comment]
I just now implemented it in https://deploy-preview-35--wai-wcag-redesign.netlify.app/understanding/

I think medium+ priority to adjust the headings and lists of the guidelines and SC.

lower priority to pull out Understanding conformance

**Comment by shawna-slh** [comment]
implemented in https://github.com/w3c/wcag-redesign/pull/38
