### ISSUE TITLE
[Understanding & Techniques index pages] expand-collapse

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag-redesign#7]
format with expand-collapse like https://www.w3.org/WAI/WCAG2/supplemental/#-cognitive-accessibility-guidance

Expand/Collapse All buttons are added and wired up with some [client side JavaScript](https://github.com/w3c/wai-website-theme/blob/master/assets/scripts/main.js#L305-L367)

**Comment by michael-n-cooper** [comment]
I need the HTML that should be output, and URIs to script and style libraries that need to be added.

**Comment by shawna-slh** [comment]
Hey @SteveALee

I'm not assigning this to you now since it's Milestone level "4 maybe easy, OK for later iteration"

(If you happen to get to it after all the other higher priority things on your To Do list, I'd be quite happy :-)

**Comment by michael-n-cooper** [comment]
I'm not sure what the question to me is so removing that label. Looking at this, it's difficult for me to tell you how difficult this will be to do, without spending time just to figure that out. Therefore I'm marking this as more difficult and I recommend not including in the immediate release target.

**Comment by shawna-slh** [comment]
moved to main wcag repo
