### ISSUE TITLE
[pending EOWG input] [Techniques nav bar] add links to the topics

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag-redesign#8]
consider putting links to the topics in the nav bar.

I was thinking about put links to the sections. I'm not sure how that would look on common configurations and also on mobile. would it be easy to do a static prototype for me to review?

I'm also wondering about an order other than ABC, such as:
* General
* Plain-Text
* HTML
* CSS
* ARIA
* Client-Side Script
* Server-Side Script
* PDF
* SMIL
* Failures

Michael says:
> In principle, we could put them in in non-alphabetical order, but it would require hard-coding. That would be a problem if we ever add a category, thinking to update that has a high forgettability probability.

> Also, we would need to create index pages for each of the categories. Those index pages would need generated lists of techniques. That's another coding effort I can't prioritize, and suggest this whole thing be an enhancement request for later.

**Comment by michael-n-cooper** [comment]
I need the exact specification of what should appear, including the HTML code, and on which pages, any contextual expectations like how it appears when the page is one of those topics, etc.

**Comment by shawna-slh** [comment]
We decided not to implement a "pager" in the techniques, since users pretty much never "walk" the techniques.

Would be good to know how often users use the index page at all? If rarely, perhaps don't even have the pager/nav bar at all for the Techniques -- and the link to all is available from the first header text, from the About page, and possibly elsewhere.

Also note that some sibling designs put the about in the nav/pager area.

Anyway, this needs work across sibling resources, which we don't have bandwidth for now. Based on small informal usability studies, I think it won't be much of a user experience hit as is.

**Comment by shawna-slh** [comment]
EOWG suggest no nav bar.
* Issue to get more input: https://github.com/w3c/wcag-redesign/issues/34
* PR with it: https://github.com/w3c/wcag-redesign/pull/33

I'll update this issue after getting more input...

**Comment by shawna-slh** [comment]
So far +1 from EOWG and WAI site manager, so closing this issue.

feel free to re-open if warranted
