### ISSUE TITLE
[Techniques About page] edit to remove redundancies and add appropriate headings

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag-redesign#9]
https://draft-wcag-redesign.netlify.app/techniques/about

* [ ] probably move the content from "[Understanding Techniques for WCAG Success Criteria](https://draft-wcag-redesign.netlify.app/understanding/understanding-techniques)" to this About Techniques page
* [ ] add a heading after the Summary
* [ ] edit to remove redundancies
* [ ] Consider existing first info or : 

```
<p>Web Content Accessibility Guidelines (WCAG) provides requirements for making websites, applications, and other digital content accessible to people with disabilities. It is introduced in the <a href="https://www.w3.org/WAI/standards-guidelines/wcag/">WCAG 2 Overview <svg focusable="false" aria-hidden="true" class="icon-different-view "><use xlink:href="/WAI/assets/images/icons.svg#icon-different-view"></use></svg></a>.</p>

<p>There are additional resources that help you understand and implement WCAG. These Techniques are one type of resource. Others are explained in the <a href="https://www.w3.org/WAI/standards-guidelines/wcag/docs/">WCAG 2 Documents <svg focusable="false" aria-hidden="true" class="icon-different-view "><use xlink:href="/WAI/assets/images/icons.svg#icon-different-view"></use></svg></a>.</p>
```

**Comment by michael-n-cooper** [comment]
I will need the specific changes you want. The best option is to make a PR on the file: https://github.com/w3c/wcag/blob/redesign/techniques/about.html

**Comment by michael-n-cooper** [comment]
There doesn't seem to be a place in the PR where I can what the exact change request is for this. And I am not able to look at a rendered version and reliably notice what you want me to notice. It is possible that I will wind up figuring that out when I walk through the PR, but that is a separate task.

**Comment by shawna-slh** [comment]
Unfortunately I was not able to make the time to make specific edit suggestions for this.

**Comment by shawna-slh** [comment]
did first pass at most and created issues for other in main wcag repo
